<?php
// 月運対応 /////////////////////////////////////////////////////////////////////////////////////
$list_mont = array( 'nu20_029', 'nu20_030', 'nu20_031', 'nu20_032', 'nu20_033', 'nu20_034',
					'nu20_035', 'nu20_036', 'nu20_037', 'nu20_038', 'nu20_039', 'nu20_040',
					'nu20_041', 'nu20_042', 'nu20_043', 'nu20_044', 'nu20_045', 'nu20_046',
					'nu20_047', 'nu20_048', 'nu20_049', 'nu20_050', 'nu20_051', 'nu20_052' );

$arrM = array( '202001', '20191203' );
if( $self->get('release_date') >= '20200423' ) {
	$arrM = array( '202005', '20200423' );
} else if( $self->get('release_date') >= '20200326' ) {
	$arrM = array( '202004', '20200326' );
} else if( $self->get('release_date') >= '20200220' ) {
	$arrM = array( '202003', '20200220' );
} else if( $self->get('release_date') >= '20200123' ) {
	$arrM = array( '202002', '20200123' );
}

$SmartyObj->assign( 'release_month', $arrM[0] );
$month_list = array( 'single' => array(), 'double' => array() );

if( $arrM[0] > 202001 )
	$month_list['single'] = getIndexData2( $list_mont, $arrM[1] );
$SmartyObj->assign( 'month_list', $month_list );


// 年運対応 /////////////////////////////////////////////////////////////////////////////////////

		$list_life = array( 'nu20_005', 'nu20_009', 'nu20_013', 'nu20_017', 'nu20_021', 'nu20_025' );
		$list_love = array( 'nu20_006', 'nu20_010', 'nu20_014', 'nu20_018', 'nu20_022', 'nu20_026' );
		$list_work = array( 'nu20_007', 'nu20_011', 'nu20_015', 'nu20_019', 'nu20_023', 'nu20_027' );
		$list_meet = array( 'nu20_008', 'nu20_012', 'nu20_016', 'nu20_020', 'nu20_024', 'nu20_028' );

		$SmartyObj->assign( 'list_life', getIndexData( $list_life ) );
		$SmartyObj->assign( 'list_love', getIndexData( $list_love ) );
		$SmartyObj->assign( 'list_meet', getIndexData( $list_meet ) );
		$SmartyObj->assign( 'list_work', getIndexData( $list_work ) );


// 他社年運対応 /////////////////////////////////////////////////////////////////////////////////////

// メニュー情報
$ExtraData = array(
	'101' => array( 'chara' => 'a', 
		'menu_title' => '雨宮零が花鳥推命で占う【2020年のあなた】恋運気/結婚/仕事/財/転機',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/stw/ray_stw/inp0016.html',
		'contents_id'   => 'ray_stw', 'img_name'   => 'stw_ray', 'teller_name'   => '雨宮零',
		'menu_price' => '1500',   'menu_discount' => '1300', 'release_date'  => '20190101',
	),
	'102' => array( 'chara' => 'a', 
		'menu_title' => '安斎流スペシャル鑑定【あなたの2020年/完全版】10大運命*幸福指南書',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/zap/anzai_zap/input/az5008a.html',
		'contents_id'   => 'anzai_zap', 'img_name'   => 'zap_anzai', 'teller_name'   => '安斎勝洋',
		'menu_price' => '1500',   'menu_discount' => '1275', 'release_date'  => '20190101',

	),
	
	'201' => array( 'chara' => 'k', 
		'menu_title' => '光と影のカードで見る2020年◆あなたの職、人、恋・結婚、成功と幸せ',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/stw/wkaori/html/inp/inp0029.html',
		'contents_id'   => 'wkaori_stw', 'img_name'   => 'stw_wkaori', 'teller_name'   => '香',
		'menu_price' => '1200',   'menu_discount' => '1000', 'release_date'  => '20190101',
	),
	'202' => array( 'chara' => 'k', 
		'menu_title' => '鏡リュウジが占う！【あなたの2020年】人生・恋愛・仕事～細密鑑定書',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/zap/complete_zap/input/cm5026a.html',
		'contents_id'   => 'complete_zap', 'img_name'   => 'zap_complete', 'teller_name'   => '鏡リュウジ（特別価格）',
		'menu_price' => '1500',   'menu_discount' => '1200', 'release_date'  => '20190101',
	),
	'203' => array( 'chara' => 'k', 
		'menu_title' => '鏡リュウジがカードで究明【2020年あなたの運命⇒悔いなき歩み方】',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/bell/ksoul/free/inp/ks1285_inp.html',
		'contents_id'   => 'ksoul_bel', 'img_name'   => 'bel_ksoul', 'teller_name'   => '鏡リュウジ',
		'menu_price' => '1500',   'menu_discount' => '1200', 'release_date'  => '20190101',
	),
	'204' => array( 'chara' => 'k', 
		'menu_title' => '【星座が告げる】2020年あなたの未来を“鏡リュウジ”が全解読！',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/bell/poseiza/free/inp/se1161_inp.html',
		'contents_id'   => 'poseiza_bel', 'img_name'   => 'bel_ksoul', 'teller_name'   => '鏡リュウジ',
		'menu_price' => '1500',   'menu_discount' => '1200', 'release_date'  => '20190101',
	),
	'205' => array( 'chara' => 'k', 
		'menu_title' => '鏡リュウジ幸運約束占◆2020年の星物語【愛/結婚/職/財/人】のすべて',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/stw/kgm12/html/inp/inp0053.html',
		'contents_id'   => 'kgm12_stw', 'img_name'   => 'stw_kgm12', 'teller_name'   => '鏡リュウジ',
		'menu_price' => '2000',   'menu_discount' => '1500', 'release_date'  => '20190101',
	),
	'206' => array( 'chara' => 'k', 
		'menu_title' => '2019年残り＋2021年前半も【鏡リュウジ責任編集】2020年あなたの運命',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/rcm/ryuji/inp129.html',
		'contents_id'   => 'ryuji_rcm', 'img_name'   => 'rcm_ryuji', 'teller_name'   => '鏡リュウジ',
		'menu_price' => '2000',   'menu_discount' => '1800', 'release_date'  => '20190101',
	),
	'207' => array( 'chara' => 'k', 
		'menu_title' => '日英超一流占術家が占う！【恋・結婚・仕事・お金】2020年運命の全貌',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/rcm/herbal/inp181.html',
		'contents_id'   => 'herbal_rcm', 'img_name'   => 'rcm_herbal', 'teller_name'   => '鏡リュウジ＋E.ブルーク',
		'menu_price' => '1500',   'menu_discount' => '1100', 'release_date'  => '20190101',
	),
	'208' => array( 'chara' => 'k', 
		'menu_title' => '12ハウス全占断◆運命の「月」が告げる2020年～人生何がどう変わる？',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/rcm/tsukiyomi_rcm/inp075.html',
		'contents_id'   => 'tsukiyomi_rcm', 'img_name'   => 'rcm_tsukiyomi', 'teller_name'   => '鏡リュウジ',
		'menu_price' => '2000',   'menu_discount' => '1650', 'release_date'  => '20191226',
	),
	'209' => array( 'chara' => 'k', 
		'menu_title' => '2020この恋どうなる？～あの人の本音と変化/決定的進展/年末のふたり',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/rcm/ryuji/inp134.html',
		'contents_id'   => 'ryuji_rcm', 'img_name'   => 'rcm_ryuji', 'teller_name'   => '鏡リュウジ',
		'menu_price' => '1500',   'menu_discount' => '1350', 'release_date'  => '20191226',
	),
	'210' => array( 'chara' => 'k', 
		'menu_title' => '驚愕！ 予言が次々現実になる◆2020年あなたの運命～激動と幸福の1年',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/com/kcc/5015.html',
		'contents_id'   => 'kcc_com', 'img_name'   => 'com_kcc', 'teller_name'   => '叶ここ',
		'menu_price' => '1100',   'menu_discount' => '900', 'release_date'  => '20191226',
	),
	'211' => array( 'chara' => 'k', 
		'menu_title' => '大感謝！　花凛が占う【あなたの2020年の運命】結婚/財/職/全幸福',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/mkb/karin/ks64/index.html',
		'contents_id'   => 'karin_mkb', 'img_name'   => 'mkb_karin', 'teller_name'   => '花凛',
		'menu_price' => '1500',   'menu_discount' => '1200', 'release_date'  => '20190101',
	),
	'212' => array( 'chara' => 'k', 
		'menu_title' => '2020年～2021年前半【恋、仕事、財、人生】銀座の母・22の運命予言',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/rcm/ginza_rcm/inp143.html',
		'contents_id'   => 'ginza_rcm', 'img_name'   => 'rcm_ginza', 'teller_name'   => '銀座の母',
		'menu_price' => '2200',   'menu_discount' => '1980', 'release_date'  => '20190101',
	),
	'213' => array( 'chara' => 'k', 
		'menu_title' => '銀座の母がズバリ！　2020～2021前半あなたの全出来事・運命・18項目',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/rcm/ginsei/html/inp/inp183.html',
		'contents_id'   => 'ginsei_rcm', 'img_name'   => 'rcm_ginsei', 'teller_name'   => '銀座の母',
		'menu_price' => '1500',   'menu_discount' => '1100', 'release_date'  => '20191226',
	),
	'214' => array( 'chara' => 'k', 
		'menu_title' => 'これぞ「銀座の母」の的中鑑定！　全30項目・2020年あなたの運命',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/rcm/ginzanohaha/html/inp/inp378.html',
		'contents_id'   => 'ginzanohaha_rcm', 'img_name'   => 'rcm_ginzanohaha', 'teller_name'   => '銀座の母',
		'menu_price' => '2000',   'menu_discount' => '1600', 'release_date'  => '20191226',
	),
	'215' => array( 'chara' => 'k', 
		'menu_title' => '2020年末＆3年後[本音/関係変化/結婚]あなたとあの人どうなってる？',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/rcm/ginza_rcm/inp141.html',
		'contents_id'   => 'ginza_rcm', 'img_name'   => 'rcm_ginza', 'teller_name'   => '銀座の母',
		'menu_price' => '1500',   'menu_discount' => '1350', 'release_date'  => '20191226',
	),
	'216' => array( 'chara' => 'k', 
		'menu_title' => 'ケントナカイ幸福占【2020年のあなたの全運勢】恋/結婚/仕事/人/財',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/stw/vtona/inp0034.html',
		'contents_id'   => 'vtona_stw', 'img_name'   => 'stw_vtona', 'teller_name'   => 'ケントナカイ',
		'menu_price' => '1500',   'menu_discount' => '1300', 'release_date'  => '20190101',
	),
	'217' => array( 'chara' => 'k', 
		'menu_title' => '【惑星集中】今一番頼りたい占術家・賢龍が導く2020年◆好機/恋/結婚',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/stw/kenryuu/html/inp/inp0016.html',
		'contents_id'   => 'kenryuu_stw', 'img_name'   => 'stw_kenryuu', 'teller_name'   => '賢龍',
		'menu_price' => '1500',   'menu_discount' => '1300', 'release_date'  => '20191226',
	),
	'218' => array( 'chara' => 'k', 
		'menu_title' => '2020年の運勢【人生まるわかり鑑定】成長/飛躍/運気を上げる助言',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/stw/koumei/menu/20.html',
		'contents_id'   => 'koumei_stw', 'img_name'   => 'stw_koumei', 'teller_name'   => '光明',
		'menu_price' => '1500',   'menu_discount' => '1300', 'release_date'  => '20191226',
	),
	'219' => array( 'chara' => 'k', 
		'menu_title' => '心酔者続出◆幸運の連鎖を招く特別占【2020年あなたの運命】SP鑑定',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/zap/koryu_zap/input/ko5003a.html',
		'contents_id'   => 'koryu_zap', 'img_name'   => 'zap_koryu', 'teller_name'   => '胡龍幸子',
		'menu_price' => '1500',   'menu_discount' => '1275', 'release_date'  => '20191226',
	),
	
	'301' => array( 'chara' => 's', 
		'menu_title' => '2020年運も“津田沼の坂井さん”に聞け！◆大ヒット御礼・幸福祈願占',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/mkb/sakai/sk48/index.html',
		'contents_id'   => 'sakai_mkb', 'img_name'   => 'mkb_sakai', 'teller_name'   => '坂井穂介',
		'menu_price' => '1800',   'menu_discount' => '1500', 'release_date'  => '20190101',
	),
	'302' => array( 'chara' => 's', 
		'menu_title' => 'ジーニーが贈る★2020年あなたの運勢【詳細幸福鑑定】恋/仕事/お金',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/stw/genie3/html/inp/inp0034.html',
		'contents_id'   => 'genie3_stw', 'img_name'   => 'stw_genie3', 'teller_name'   => 'ジーニー',
		'menu_price' => '1500',   'menu_discount' => '1300', 'release_date'  => '20190101',
	),
	'303' => array( 'chara' => 's', 
		'menu_title' => '黒猫が占う2020◆あなたに届く大きな愛/人生の喜び/次の挑戦と報酬！',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/com/cat/0047.html',
		'contents_id'   => 'cat_com', 'img_name'   => 'com_cat', 'teller_name'   => 'ジューン澁澤',
		'menu_price' => '1100',   'menu_discount' => '900', 'release_date'  => '20190101',
	),
	'304' => array( 'chara' => 's', 
		'menu_title' => '2020年あなたを待ち受ける◆新たな幸福/不思議な出会い/手放せる苦痛',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/com/aut/3282.html',
		'contents_id'   => 'aut_com', 'img_name'   => 'com_aut', 'teller_name'   => 'ジューン澁澤',
		'menu_price' => '1200',   'menu_discount' => '1000', 'release_date'  => '20191226',
	),
	'305' => array( 'chara' => 's', 
		'menu_title' => '1年グラフ付◆新宿の母“渾身鑑定”2020年あなたの運命≪全網羅≫',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/bell/polhaha/free/inp/ss1148_inp.html',
		'contents_id'   => 'polhaha_bel', 'img_name'   => 'bel_polhaha', 'teller_name'   => '新宿の母',
		'menu_price' => '1500',   'menu_discount' => '1300', 'release_date'  => '20190101',
	),
	'306' => array( 'chara' => 's', 
		'menu_title' => '水晶玉子Presents2020年あなたの全運命◆寿ゾーンで占う恋／仕事／財',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/zap/kotobuki_zap/input/kb5004a.html',
		'contents_id'   => 'kotobuki_zap', 'img_name'   => 'zap_kotobuki', 'teller_name'   => '水晶玉子',
		'menu_price' => '1500',   'menu_discount' => '1275', 'release_date'  => '20190101',
	),
	'307' => array( 'chara' => 's', 
		'menu_title' => '水晶玉子が贈る2020年上半期“あなたの運命詳細鑑定！',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/bell/postamako/free/inp/ms1081_inp.html',
		'contents_id'   => 'postamako_bel', 'img_name'   => 'bel_postamako', 'teller_name'   => '水晶玉子',
		'menu_price' => '1500',   'menu_discount' => '1300', 'release_date'  => '20190101',
	),
	'308' => array( 'chara' => 's', 
		'menu_title' => '水晶玉子が詳細鑑定【2020年あなた】恋/結婚/職/対人/財/訪れる幸福',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/stw/fruits/input/fr00112.html',
		'contents_id'   => 'fruits_stw', 'img_name'   => 'stw_fruits', 'teller_name'   => '水晶玉子',
		'menu_price' => '1500',   'menu_discount' => '1300', 'release_date'  => '20190101',
	),
	'309' => array( 'chara' => 's', 
		'menu_title' => '水晶玉子◆2020年感涙予言！【あなたを待つ9つの運命】恋/仕事/恵み',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/zap/toriental_zap/input/ot3208a.html',
		'contents_id'   => 'toriental_zap', 'img_name'   => 'zap_toriental', 'teller_name'   => '水晶玉子',
		'menu_price' => '1200',   'menu_discount' => '1020', 'release_date'  => '20191226',
	),
	'310' => array( 'chara' => 's', 
		'menu_title' => '人生が大きく動き出す【激変の2020年】恋愛/結婚/仕事運はどうなる？',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/stw/sango/inp0044.html',
		'contents_id'   => 'sango_stw', 'img_name'   => 'stw_sango', 'teller_name'   => '千田歌秋',
		'menu_price' => '1500',   'menu_discount' => '1300', 'release_date'  => '20190101',
	),
	
	'401' => array( 'chara' => 't', 
		'menu_title' => '濃厚3000字◆2020年ふたりに待つ出来事/接近/変化/決断……最終関係',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/rcm/takemoto/inp117.html',
		'contents_id'   => 'takemoto_rcm', 'img_name'   => 'rcm_takemoto', 'teller_name'   => '竹本光晴',
		'menu_price' => '1200',   'menu_discount' => '920', 'release_date'  => '20191226',
	),
	'402' => array( 'chara' => 't', 
		'menu_title' => '浅草橋の母がズバリ断言！◆2020年、あなたの運命＆出来事◆全10項目',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/zap/tsuchiya_zap/input/tc5005a.html',
		'contents_id'   => 'tsuchiya_zap', 'img_name'   => 'zap_tsuchiya', 'teller_name'   => '土屋慶真',
		'menu_price' => '1500',   'menu_discount' => '1275', 'release_date'  => '20190101',
	),
	
	'501' => array( 'chara' => 'n', 
		'menu_title' => '【生田目流姓名判断スペシャル鑑定◆あなたの2020年】恋愛/仕事/財運',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/zap/namatame_zap/input/nt5003a.html',
		'contents_id'   => 'namatame_zap', 'img_name'   => 'zap_namatame', 'teller_name'   => '生田目浩美．',
		'menu_price' => '1500',   'menu_discount' => '1275', 'release_date'  => '20191226',
	),
	
	/* '601' => array( 'chara' => 'h', 
		'menu_title' => '【あなたX歳までに結婚ですね】伴侶も特定（名/歳）入籍⇒X月X日確定',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/mcpad/hvnami/UkwTopHV000500.html',
		'contents_id'   => 'hvnami_mcp', 'img_name'   => 'mcp_hvnami', 'teller_name'   => '濱田奈美',
		'menu_price' => '1800',   'menu_discount' => '1400', 'release_date'  => '20191226',
	), */
	'602' => array( 'chara' => 'h', 
		'menu_title' => '2020年、あの人は私と「どこまで」望む？　密かな誓い◇1年後の二人',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/mkb/yutaharu/yh47/index.html',
		'contents_id'   => 'yutaharu_mkb', 'img_name'   => 'mkb_yutaharu', 'teller_name'   => 'はる',
		'menu_price' => '1500',   'menu_discount' => '1200', 'release_date'  => '20191226',
	),
	'603' => array( 'chara' => 'h', 
		'menu_title' => '奇跡の宇宙眼で大予言【2020年、あなたの絶対運命】仕事/財/ご縁/幸',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/zap/biggy_zap/input/bg5003a.html',
		'contents_id'   => 'biggy_zap', 'img_name'   => 'zap_biggy', 'teller_name'   => 'Biggy Neptune',
		'menu_price' => '1500',   'menu_discount' => '1275', 'release_date'  => '20190101',
	),
	'604' => array( 'chara' => 'h', 
		'menu_title' => '募るばかりの恋心【彼は私と交際してくれる？】2020年恋鑑定/2人の終',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/mcpad/ubuka/UkwTopUB001700.html',
		'contents_id'   => 'ubuka_mcp', 'img_name'   => 'mcp_ubuka', 'teller_name'   => 'ピュアローズうぶ花',
		'menu_price' => '1500',   'menu_discount' => '1200', 'release_date'  => '20191226',
	),
	'605' => array( 'chara' => 'h', 
		'menu_title' => '黄金期が導く【最大幸福の2020年】恋愛/仕事/金の劇的変化と注意事項',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/stw/gold/inp0034.html',
		'contents_id'   => 'gold_stw', 'img_name'   => 'stw_gold', 'teller_name'   => '黄月',
		'menu_price' => '1500',   'menu_discount' => '1300', 'release_date'  => '20190101',
	),
	'606' => array( 'chara' => 'h', 
		'menu_title' => '法演が断言します！【あなたの2020年◆重要運命】現状/恋/仕事/人生',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/zap/houen_zap/input/hp5004a.html',
		'contents_id'   => 'houen_zap', 'img_name'   => 'zap_houen', 'teller_name'   => '法演',
		'menu_price' => '1500',   'menu_discount' => '1275', 'release_date'  => '20190101',
	),
	'607' => array( 'chara' => 'h', 
		'menu_title' => '当たると噂殺到！【鳳占やかた】あなたの2020年の全運勢◆特別鑑定書',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/zap/houyakata_zap/input/hz5005a.html',
		'contents_id'   => 'houyakata_zap', 'img_name'   => 'zap_houyakata', 'teller_name'   => '鳳占やかた　伊藤行斎',
		'menu_price' => '1500',   'menu_discount' => '1275', 'release_date'  => '20190101',
	),
	'608' => array( 'chara' => 'h', 
		'menu_title' => '恋・出逢い・仕事・お金【究極の2020年運】あなたの全運命と全出来事',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/rcm/hoshihitomi/inp206.html',
		'contents_id'   => 'hoshihitomi_rcm', 'img_name'   => 'rcm_hoshihitomi', 'teller_name'   => '星ひとみ',
		'menu_price' => '1500',   'menu_discount' => '1100', 'release_date'  => '20191226',
	),
	'609' => array( 'chara' => 'h', 
		'menu_title' => '【晩年安泰/飛躍叶える61項】あなたの全人生＆全宿縁◆愛/職/財/余生',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/tel/hbena/UkwTopHB009900.html',
		'contents_id'   => 'hbena_tel', 'img_name'   => 'tel_hbena', 'teller_name'   => '星乃エナ',
		'menu_price' => '5800',   'menu_discount' => '5300', 'release_date'  => '20190101',
	),
	'610' => array( 'chara' => 'h', 
		'menu_title' => '【2020年運命＋全生涯を知る27項】あなたの1/5/10年後⇒晩年◆網羅SP',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/tel/hbena/UkwTopHB000100.html',
		'contents_id'   => 'hbena_tel', 'img_name'   => 'tel_hbena', 'teller_name'   => '星乃エナ',
		'menu_price' => '2600',   'menu_discount' => '2100', 'release_date'  => '20190101',
	),
	
	'701' => array( 'chara' => 'm', 
		'menu_title' => '真木あかりが届ける【2020年あなたの幸せ】職/対人/財/恋/結婚/成功',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/stw/akr/html/inp/inp0025.html',
		'contents_id'   => 'akr_stw', 'img_name'   => 'stw_akr', 'teller_name'   => '真木あかり',
		'menu_price' => '1500',   'menu_discount' => '1300', 'release_date'  => '20190101',
	),
	'702' => array( 'chara' => 'm', 
		'menu_title' => 'ズバリ的中！【2020年あなたの恋と結婚】運勢/モテ度/年内婚の確率',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/mkb/inmaya/im27/index.html',
		'contents_id'   => 'inmaya_mkb', 'img_name'   => 'mkb_inmaya', 'teller_name'   => '摩弥',
		'menu_price' => '1200',   'menu_discount' => '1000', 'release_date'  => '20190101',
	),
	'703' => array( 'chara' => 'm', 
		'menu_title' => '星座×血液型が幸運をもたらす◆2020年あなたの恋/結婚/仕事/対人/財',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/stw/event/mita/html/inp/inp0070.html',
		'contents_id'   => 'mita_stw', 'img_name'   => 'stw_mita', 'teller_name'   => '三田モニカ',
		'menu_price' => '1500',   'menu_discount' => '1200', 'release_date'  => '20190101',
	),
	'704' => array( 'chara' => 'm', 
		'menu_title' => 'こんなにいいこと待っている！【笑顔の2020年運】恋/仕事/お金/結婚',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/stw/minami/inp0028.html',
		'contents_id'   => 'minami_stw', 'img_name'   => 'stw_minami', 'teller_name'   => '三波ちぇこ',
		'menu_price' => '1500',   'menu_discount' => '1300', 'release_date'  => '20190101',
	),
	
	'801' => array( 'chara' => 'y', 
		'menu_title' => '極秘血脈の禁断能力で全判明！【あなたの2020年】恋愛/仕事/対人/財',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/mkb/yukiho/yk29/index.html',
		'contents_id'   => 'yukiho_mkb', 'img_name'   => 'mkb_yukiho', 'teller_name'   => '雪穂',
		'menu_price' => '1500',   'menu_discount' => '1200', 'release_date'  => '20190101',
	),
	
	'901' => array( 'chara' => 'r', 
		'menu_title' => '2020年、彼とあなたの恋はどうなる？【完全予言】心境の変化と転機',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/zap/rion_zap/input/ri4203a.html',
		'contents_id'   => 'rion_zap', 'img_name'   => 'zap_rion', 'teller_name'   => 'R.I.O.N',
		'menu_price' => '1200',   'menu_discount' => '1020', 'release_date'  => '20191226',
	),
	'902' => array( 'chara' => 'r', 
		'menu_title' => '魔法のカードに聞く【2020年の運勢】恋/職/金/人/訪れるバラ色の日々',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/stw/dmjc/html/inp/inp0021.html',
		'contents_id'   => 'dmjc_stw', 'img_name'   => 'stw_dmjc', 'teller_name'   => 'ルネ・ヴァン・ダール・ワタナベ',
		'menu_price' => '1200',   'menu_discount' => '1000', 'release_date'  => '20190101',
	),
	'903' => array( 'chara' => 'r', 
		'menu_title' => '魔術師のカードが告げる2020年あなたの運命◆仕事/恋/お金/幸福まで',
		'menu_url'   => 'https://charge-fortune.yahoo.co.jp/zap/thoth_zap/input/tt5005a.html',
		'contents_id'   => 'thoth_zap', 'img_name'   => 'zap_thoth', 'teller_name'   => 'レオン・サリラ',
		'menu_price' => '1500',   'menu_discount' => '1200', 'release_date'  => '20191226',
	),
);

$SmartyObj->assign( 'list_extra', getIndexData3( $ExtraData ) );
$list_extra2 = array( 'a' => 0, 'k' => 0, 's' => 0, 't' => 0, 'n' => 0, 'h' => 0, 'm' => 0, 'y' => 0, 'r' => 0, 'w' => 0 );
foreach( $ExtraData as $row ) {
	if( $row['release_date'] > $self->get('release_date') ) continue;
	$list_extra2[ $row['chara'] ] = 1;
}
$SmartyObj->assign( 'list_extra2', $list_extra2 );


?>
